language: python
sudo: false

env:
  global:
    - PIP_DEPS="pytest>=3.6.0 coveralls pytest-cov flake8"

python:
  - '2.7'
  - '3.6'

install:
- travis_retry pip install $PIP_DEPS
- travis_retry pip install -r requirements.txt
- travis_retry pip install -e .

script:
- make flake8
- xvfb-run make test

after_success:
- coveralls
